import re
import os
from pathlib import Path
from urllib.parse import urlunparse, urlparse
import dotenv


SCRIPT_PATH = Path(__file__).resolve()

#
# Directories
#

VALIDATION_DIR = "validation"
INTERMEDIATE_DIR = "intermediate"
OUTPUT_DIR = "output"

#
# Input files
#

# Files to be read from Hugo's output directory, which is by default
# the directory named `public` in the Hugo project directory
# Required input: complete list of URIs generated by Hugo
HUGO_GENERATED_URLS_FILE = "_urls"
# Optional input: list of alias mappings generated by Hugo
HUGO_GENERATED_ALIASES_FILE = "_aliases"

# Optional input: one or more files comprising a list of redirects
# in VALIDATION_DIR with the following file name prefix
VALIDATION_FILE_NAME_PREFIX = ""

#
# Generated files
#

# Access log processed into a CSV file
ACCESS_LOG_PROCESSED_FILE = "access_log.csv"

GENERATED_FILE_NAME_PREFIX = ""  # f"{ORIGINAL_HOSTNAME}_"


# Access log column names
REMOTE_ADDR = "Remote address"
REMOTE_USER = "Remote user"
REQUEST_TIMESTAMP = "Request timestamp"
REQUEST_METHOD = "Request method"
REQUEST_URI = "Request URI"
REQUEST_REFERER = "Request Referer"
REQUEST_USER_AGENT = "Request User Agent"
RESPONSE_STATUS = "Response Status"
RESPONSE_BYTES_SENT = "Response Body Bytes Sent"

# Generated column names
REQUEST_URI_WITHOUT_QUERY = "URI without query"
REQUEST_URI_CANONICAL = "Canonical URI"
ACCESS_COUNT = "Total Access Count"

# Generated redirects
REDIRECT_URI = "Redirect URI"
REDIRECT_STATUS = "Redirect status"

# Redirect file columns
REDIRECTS_FILE_REQUEST_URI = "path"
REDIRECTS_FILE_REDIRECT_URI = "target"
REDIRECTS_FILE_REDIRECT_STATUS = "status"

COLUMNS_ACCESS_LOG = [
    REMOTE_ADDR,
    REMOTE_USER,
    REQUEST_TIMESTAMP,
    REQUEST_METHOD,
    REQUEST_URI,
    RESPONSE_STATUS,
    RESPONSE_BYTES_SENT,
    REQUEST_REFERER,
    REQUEST_USER_AGENT,
]

COLUMNS_FOR_ANALYSIS = [
    REQUEST_URI,
    REQUEST_TIMESTAMP,
    REQUEST_METHOD,
    RESPONSE_STATUS,
    REQUEST_REFERER,
    REQUEST_USER_AGENT,
]

COLUMNS_PROCESSING = COLUMNS_FOR_ANALYSIS + [
    REQUEST_URI_CANONICAL,
    ACCESS_COUNT,
]

COLUMNS_REDIRECTS = [
    REDIRECT_URI,
    REDIRECT_STATUS,
]

COLUMNS_COMPLETE = COLUMNS_PROCESSING + COLUMNS_REDIRECTS

COLUMN_MAP_REDIRECTS_FILE = {
    REQUEST_URI: REDIRECTS_FILE_REQUEST_URI,
    REDIRECT_URI: REDIRECTS_FILE_REDIRECT_URI,
    REDIRECT_STATUS: REDIRECTS_FILE_REDIRECT_STATUS,
}

# Validate redirects
VALIDATION_STATUS_INITIAL = "Validation status initial"
VALIDATION_STATUS_FINAL = "Validation status final"

HTTP_STATUS_OK = 200
HTTP_STATUS_REDIRECT = 301
HTTP_STATUS_NOT_FOUND = 404
